#!/bin/bash

curl -sSL https://install.python-poetry.org | python3 -
poetry --version
poetry completions bash >> ~/.bash_completion
poetry completions zsh > ~/.zfunc/_poetry


# vim: set ts=4 sw=4 tw=92 ss=0 ft=sh et ai :
